<a href="https://colab.research.google.com/github/AymanNasser/Random-DNN-Notebooks/blob/master/Manipulating_Tensors_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
a = torch.ones(5) # Creates a one-dimensional tensor of size 5 filled with 1s
a

tensor([1., 1., 1., 1., 1.])

In [3]:
a[0], a[1]

(tensor(1.), tensor(1.))

In [4]:
a[3] = 5.5
a

tensor([1.0000, 1.0000, 1.0000, 5.5000, 1.0000])

In [5]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [6]:
# Equivalent to the above is a 2d tensor
points = torch.tensor([[4,1], [5,3], [2,1]])
points

tensor([[4, 1],
        [5, 3],
        [2, 1]])

In [7]:
points.shape

torch.Size([3, 2])

In [8]:
points[1,0]

tensor(5)

In [9]:
print(points[1:-1, :])

tensor([[5, 3]])


In [10]:
img_t = torch.rand(3, 5, 5) 
batch_t = torch.rand(2, 3, 5, 5) # Batch of imgs of size=2, each is 5*5*3 
img_t

tensor([[[0.4756, 0.3359, 0.9558, 0.9558, 0.1215],
         [0.0064, 0.5420, 0.8185, 0.5226, 0.2910],
         [0.5894, 0.4047, 0.9764, 0.0067, 0.4743],
         [0.7389, 0.8112, 0.9802, 0.7731, 0.0292],
         [0.3993, 0.2816, 0.9524, 0.9879, 0.2918]],

        [[0.7887, 0.8138, 0.2113, 0.8741, 0.0376],
         [0.5451, 0.2126, 0.0823, 0.4024, 0.9436],
         [0.8451, 0.8789, 0.8004, 0.1067, 0.1491],
         [0.6406, 0.7792, 0.8999, 0.8131, 0.7497],
         [0.6626, 0.8595, 0.8575, 0.9736, 0.0260]],

        [[0.1753, 0.9689, 0.5058, 0.5736, 0.4672],
         [0.9552, 0.0085, 0.0208, 0.8564, 0.1550],
         [0.9215, 0.5382, 0.5493, 0.9721, 0.0100],
         [0.1022, 0.8956, 0.8128, 0.6681, 0.5530],
         [0.9909, 0.4911, 0.9395, 0.9721, 0.0028]]])

In [11]:
img_gray_naive = img_t.mean(-3) # same as img_t.mean(0) ==> taking the mean across the third dim from the end (-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape, img_gray_naive, batch_gray_naive

(torch.Size([5, 5]),
 torch.Size([2, 5, 5]),
 tensor([[0.4799, 0.7062, 0.5576, 0.8012, 0.2088],
         [0.5023, 0.2544, 0.3072, 0.5938, 0.4632],
         [0.7853, 0.6073, 0.7754, 0.3618, 0.2111],
         [0.4939, 0.8287, 0.8976, 0.7514, 0.4440],
         [0.6843, 0.5441, 0.9165, 0.9779, 0.1069]]),
 tensor([[[0.3575, 0.5528, 0.6358, 0.6757, 0.5824],
          [0.6371, 0.4494, 0.5726, 0.2751, 0.3590],
          [0.5034, 0.7195, 0.7356, 0.5577, 0.4852],
          [0.5164, 0.3467, 0.5698, 0.2778, 0.4152],
          [0.6978, 0.2657, 0.6832, 0.7044, 0.5556]],
 
         [[0.3906, 0.6033, 0.8199, 0.4297, 0.5586],
          [0.5236, 0.4384, 0.5302, 0.5059, 0.4634],
          [0.5382, 0.4344, 0.6601, 0.5368, 0.7892],
          [0.4723, 0.6268, 0.4513, 0.6048, 0.6598],
          [0.2104, 0.6823, 0.5254, 0.5049, 0.4356]]]))

In [12]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
unsquez_weights = weights.unsqueeze(-1) # Expanding the tensor dim
print(unsquez_weights.shape)
unsquez_weights = unsquez_weights.unsqueeze(-1)
print(unsquez_weights.shape)

torch.Size([3, 1])
torch.Size([3, 1, 1])


In [13]:
img_weights = img_t * unsquez_weights
img_weights

tensor([[[1.0112e-01, 7.1413e-02, 2.0320e-01, 2.0320e-01, 2.5840e-02],
         [1.3592e-03, 1.1524e-01, 1.7402e-01, 1.1111e-01, 6.1867e-02],
         [1.2531e-01, 8.6042e-02, 2.0759e-01, 1.4203e-03, 1.0084e-01],
         [1.5708e-01, 1.7246e-01, 2.0839e-01, 1.6436e-01, 6.2087e-03],
         [8.4894e-02, 5.9870e-02, 2.0248e-01, 2.1002e-01, 6.2035e-02]],

        [[5.6406e-01, 5.8202e-01, 1.5115e-01, 6.2517e-01, 2.6896e-02],
         [3.8989e-01, 1.5203e-01, 5.8885e-02, 2.8783e-01, 6.7483e-01],
         [6.0440e-01, 6.2859e-01, 5.7245e-01, 7.6278e-02, 1.0665e-01],
         [4.5815e-01, 5.5730e-01, 6.4363e-01, 5.8153e-01, 5.3618e-01],
         [4.7388e-01, 6.1471e-01, 6.1325e-01, 6.9633e-01, 1.8594e-02]],

        [[1.2658e-02, 6.9955e-02, 3.6517e-02, 4.1410e-02, 3.3733e-02],
         [6.8968e-02, 6.1609e-04, 1.5048e-03, 6.1830e-02, 1.1191e-02],
         [6.6534e-02, 3.8860e-02, 3.9661e-02, 7.0188e-02, 7.2127e-04],
         [7.3769e-03, 6.4661e-02, 5.8687e-02, 4.8236e-02, 3.9927e-02],
  

In [14]:
batch_weights = (batch_t * unsquez_weights) # Although unsquez_weights tensor isn't in the same dim of batch_t tensor, but due to broadcasting, multiplication occurred
batch_weights

tensor([[[[1.4671e-01, 1.7176e-01, 1.6440e-01, 8.3075e-02, 1.9023e-01],
          [9.9797e-02, 1.9790e-01, 2.0549e-01, 5.5336e-02, 7.6109e-02],
          [9.8548e-02, 1.4793e-01, 1.9543e-01, 1.4980e-01, 5.4685e-02],
          [1.1226e-01, 1.7315e-01, 1.9314e-01, 6.7793e-02, 1.1163e-01],
          [1.6469e-01, 1.4282e-01, 1.2361e-01, 1.4363e-01, 1.0322e-01]],

         [[3.0554e-02, 1.5185e-01, 2.6183e-01, 5.9956e-01, 7.1257e-02],
          [6.6595e-01, 2.6085e-01, 2.5928e-01, 2.1291e-01, 1.0365e-01],
          [4.3571e-01, 5.1213e-01, 7.1280e-01, 5.8461e-01, 4.7884e-01],
          [5.1426e-01, 3.4083e-02, 6.2519e-02, 1.9352e-01, 4.8383e-01],
          [3.8983e-01, 8.5108e-02, 6.2120e-01, 6.3947e-01, 1.9056e-01]],

         [[2.4538e-02, 4.6072e-02, 5.5459e-02, 5.7623e-02, 5.4354e-02],
          [3.6874e-02, 3.7994e-03, 2.8058e-02, 1.9304e-02, 4.1439e-02],
          [3.1580e-02, 5.3898e-02, 2.1007e-02, 1.0906e-02, 3.8186e-02],
          [2.1815e-02, 1.2857e-02, 5.1524e-02, 1.7615e-02, 3

In [15]:
random_tens = torch.tensor([4,4,2,5], names=['channels']) # Naming a tensor
random_tens

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:840.)
  """Entry point for launching an IPython kernel.


tensor([4, 4, 2, 5], names=('channels',))

In [16]:
random_tens.dtype

torch.int64

In [17]:
random_tens = torch.zeros(10,2).to(dtype=torch.float32)
random_tens.dtype

torch.float32

In [18]:
random_tens.storage_offset(), random_tens.size(), random_tens.stride()

(0, torch.Size([10, 2]), (2, 1))

In [24]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [26]:
points_cpu = points_gpu.to(device='cpu')
points_cpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
numpy_arr = np.array([[1., 1., 1., 1.],
                     [1., 5., 5., 1.],
                     [1., 2., 2., 1.]])
numpy_arr

array([[1., 1., 1., 1.],
       [1., 5., 5., 1.],
       [1., 2., 2., 1.]])

In [37]:
tensor_ = torch.from_numpy(numpy_arr).to(dtype=torch.float32).to(device='cuda') # Converting a numpy array to a torch tensor then moving the tensor on the GPU
tensor_

tensor([[1., 1., 1., 1.],
        [1., 5., 5., 1.],
        [1., 2., 2., 1.]], device='cuda:0')

In [38]:
torch.save(tensor_, '../tmp/tensor.t') # Saving our tensor 

In [39]:
tensor_again_ = torch.load('../tmp/tensor.t')
tensor_again_

tensor([[1., 1., 1., 1.],
        [1., 5., 5., 1.],
        [1., 2., 2., 1.]], device='cuda:0')

In [49]:
b = tensor_.view(4,3)
b, b.storage(), tensor_.storage()

(tensor([[1., 1., 1.],
         [1., 1., 5.],
         [5., 1., 1.],
         [2., 2., 1.]], device='cuda:0'),  1.0
  1.0
  1.0
  1.0
  1.0
  5.0
  5.0
  1.0
  1.0
  2.0
  2.0
  1.0
 [torch.cuda.FloatStorage of size 12],  1.0
  1.0
  1.0
  1.0
  1.0
  5.0
  5.0
  1.0
  1.0
  2.0
  2.0
  1.0
 [torch.cuda.FloatStorage of size 12])

In [51]:
b = torch.cos(torch.tensor([0.9]))
b

tensor([0.6216])